spring:
  application:
    name: bilibili-api

  datasource:
    url: jdbc:mysql://localhost:3306/bilibili?useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver